python-webservice-demo:
  fullnameOverride: python-webservice-demo

  env:
    # This connection string used for demo purposes only.
    # DO NOT use this approach in real environments!
    DATABASE_URL: mysql+pymysql://demo:demo@mysql/demo

  deploymentStrategy:
    type: RollingUpdate
    rollingUpdate:
      unavailable: 40%

  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: python-webservice-demo.local
        paths:
          - path: /
            pathType: ImplementationSpecific
