python-webservice-demo:
  deploymentStrategy:
    type: RollingUpdate
    rollingUpdate:
      unavailable: 40%

  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: python-webservice-demo.local
        paths:
          - path: /
            pathType: ImplementationSpecific
