global:
  namespace: demo
  project: demo
  repo:
    url: https://github.com/vladimir-babichev/python-webservice-demo
    revision: HEAD
  helm:
    version: v3
    valueFiles:
      - values.yaml

argocd-apps:
  applications:
    python-webservice-demo:
      path: k8s/demo/python-webservice-demo
