version: "3"

env:
  CONTAINER_REGISTRY: ghcr.io/vladimir-babichev
  APP_NAME: python-webservice-demo
  APP_VERSION:
    sh: |
      cat {{ .ROOT_DIR }}/app/VERSION

tasks:
  setup:
    desc: Setup pre-commit
    cmds:
      - pre-commit install --install-hooks

  precommit:
    desc: Execute pre-commit for modified files
    cmds:
      - SKIP={{ .PRE_COMMIT_SKIP }} pre-commit run --color=always --show-diff-on-failure --from-ref origin/main --to-ref HEAD

  precommit-all:
    desc: Execute pre-commit for all files
    cmds:
      - SKIP={{ .PRE_COMMIT_SKIP }} pre-commit run --color=always --show-diff-on-failure --all-files

  unittest:
    desc: Run application unit tests
    cmds:
      - cd {{ .ROOT_DIR }}/app && python -m unittest discover

  docker-build:
    desc: Build Docker Image
    cmds:
      - docker build -t {{ .CONTAINER_REGISTRY }}/{{ .APP_NAME }}:{{ .APP_VERSION }} {{ .ROOT_DIR }}/app

  docker-run:
    desc: Run Docker container
    cmds:
      - |
        docker run \
          --name {{ .APP_NAME }} \
          --rm -p 8080:8080 -ti \
          -e WEB_RELOAD=true \
          -v {{ .ROOT_DIR }}/app:/app \
          {{ .CLI_ARGS }} \
          {{ .CONTAINER_REGISTRY }}/{{ .APP_NAME }}:{{ .APP_VERSION }}

  compose-setup:
    desc: Setup Docker Compose environment
    cmds:
      - cp {{ .ROOT_DIR }}/app/.env.example {{ .ROOT_DIR }}/app/.env

  compose-up:
    desc: docker-compose up
    cmds:
      - docker-compose --project-directory {{ .ROOT_DIR }}/app up -d {{ .CLI_ARGS }}

  compose-down:
    desc: docker-compose down
    cmds:
      - docker-compose --project-directory {{ .ROOT_DIR }}/app down {{ .CLI_ARGS }}

  compose-logs:
    desc: docker-compose logs
    cmds:
      - docker-compose --project-directory {{ .ROOT_DIR }}/app logs {{ .CLI_ARGS }}

  minikube-up:
    desc: Bootstrap minikube cluster
    cmds:
      - minikube start
      - minikube addons enable ingress
      - "{{ .ROOT_DIR }}/scripts/bootstrap.sh"

  minikube-down:
    desc: Delete minikube cluster
    cmds:
      - minikube delete
