.domain: &x-domain "argocd.local"
.url: &x-url "https://argocd.local"

argo-cd:
  fullnameOverride: argocd
  configs:
    cm:
      application.instanceLabelKey: argocd.argoproj.io/instance
      url: *x-url
    repositories:
      argo-helm-repo:
        name: argo
        type: helm
        url: https://argoproj.github.io/argo-helm
      stable-helm-repo:
        name: stable
        type: helm
        url: https://charts.helm.sh/stable
    secret:
      # This password used for demo purposes only.
      # DO NOT use this approach in real environments!
      # `argocdServerAdminPassword: demo`
      argocdServerAdminPassword: "$2a$10$8zp1nQaryZTp22UNUitHyeH9bgCnZxTkLw24IgSTBep4d3hkz05ue"
  server:
    extraArgs:
      - --insecure
    ingress:
      ingressClassName: nginx
      enabled: true
      hosts:
        - *x-domain
      paths:
        - /

  dex:
    enabled: false

  repoServer:
    serviceAccount:
      create: true
