.domain: &x-domain "argocd.local"
.url: &x-url "https://argocd.local"

argo-cd:
  configs:
    cm:
      application.instanceLabelKey: argocd.argoproj.io/instance
      url: *x-url
    repositories:
      argo-helm-repo:
        name: argo
        type: helm
        url: https://argoproj.github.io/argo-helm
      stable-helm-repo:
        name: stable
        type: helm
        url: https://charts.helm.sh/stable
  server:
    extraArgs:
      - --insecure
    ingress:
      ingressClassName: nginx
      enabled: true
      hosts:
        - *x-domain
      paths:
        - /

  dex:
    enabled: false

  repoServer:
    serviceAccount:
      create: true
