# -- Amount of application replicas
replicaCount: 1
image:
  # -- Image repository
  repository: ghcr.io/vladimir-babichev/python-webservice-demo
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""

# -- List of image pull secrets
imagePullSecrets: []

# -- Chart name override
nameOverride: ""

# -- Chart fullname override
fullnameOverride: ""

# -- Map of Environment variables pairs defined in a `Key: Value`` format.
env: {}
# env:
#   KEY: value
#   foo: bar

# -- Secrets and/or ConfigMaps that will be loaded as environment variables.
envFrom: []
# envFrom:
#   - configMapRef:
#       name: config-map-name
#   - secretRef:
#       name: secret-name

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- Annotations added to the pod
podAnnotations: {}

# -- Pod security context
podSecurityContext: {}
#   fsGroup: 2000

securityContext: {}
#   capabilities:
#     drop:
#     - ALL
#   readOnlyRootFilesystem: true
#   runAsNonRoot: true
#   runAsUser: 1000

service:
  # -- Service type
  type: ClusterIP
  # -- Service port
  port: 8080

# -- Configure deployment upgrade strategy
deploymentStrategy:
  # -- Valid values are Recreate (default) and RollingUpdate.
  type: Recreate
  rollingUpdate:
    # -- Set RollingUpdate max unavailable
    unavailable:
    # -- Set RollingUpdate max surge
    surge:

ingress:
  # -- Specifies whether a ingress resource should be created
  enabled: false
  className: ""
  annotations: {}
  #   kubernetes.io/ingress.class: nginx
  #   kubernetes.io/tls-acme: "true"

  # -- Hosts configuration
  # @default -- Check [values.yaml](../values.yaml) for details.
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific

  # -- TLS configuration
  # @default -- Check [values.yaml](../values.yaml) for details.
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- Application resource constraints
# @default -- Check [values.yaml](../values.yaml) for details.
resources: {}

# -- Autoscaling configuration
# @default -- Check [values.yaml](../values.yaml) for details.
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# -- Node selector
nodeSelector: {}

# -- Tollerations
tolerations: []

# -- Affinity
affinity: {}
