name: Build and Push Docker Image

on:
  push:
    path:
      - app/**

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release-docker-image:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get App version
        id: get-app-version
        run: echo "VERSION=$(cat app/VERSION)" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: app
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get-app-version.outputs.VERSION }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  release-helm-chart:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update chart version
        env:
          CHART_NAME: ${{ github.event.repository.name }}
        run: |
          export CHART_VERSION=$(cat app/VERSION)
          export APP_VERSION=$(cat app/VERSION)
          envsubst < app/deploy/chart/Chart.yaml.tpl > app/deploy/chart/Chart.yaml

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: app/deploy
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
