name: Release Artifacts

on:
  push:
    path:
      - app/**

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yaml

  release-docker-image:
    if: github.ref == 'refs/heads/main'
    needs:
      - pre-commit
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/release-docker-image.yaml

  release-helm-chart:
    if: github.ref == 'refs/heads/main'
    needs:
      - pre-commit
    permissions:
      contents: write
    uses: ./.github/workflows/release-helm-chart.yaml
